// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7: datasource URL lives here (not in the schema). Driven by DATABASE_URL.
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
