// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// migrations are dialect-specific, so keep one folder per provider.
const provider = process.env.DATABASE_PROVIDER === "postgres" ? "postgres" : "sqlite";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: `prisma/migrations/${provider}`,
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
    directUrl: process.env.DIRECT_URL,
  },
});
